# Generated by Django 3.0.3 on 2020-02-21 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20200221_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='rel_id',
            field=models.IntegerField(),
        ),
    ]
